metadata : "test_samples.tsv"
projectDir: "/sc/arion/projects/ad-omics/winston/jacusa_workspace/snakemake_testing/"
refDir : "/sc/arion/projects/ad-omics/data/references/GRCh38_references/"
editingRefDir : "/sc/arion/projects/ad-omics/data/references/editing/"
humandbDir: "/sc/arion/projects/ad-omics/data/references/editing/humandb/"

